# Generated by Django 6.1.2 on 2026-10-08 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('titulo_original', models.CharField(max_length=150)),
                ('sinopsis', models.TextField(max_length=1000)),
                ('anio_estreno', models.IntegerField()),
                ('num_episodios', models.IntegerField()),
                ('tipo', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='animes/')),
            ],
        ),
        migrations.CreateModel(
            name='Disponibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idioma_audio', models.CharField(max_length=50)),
                ('subtitulos', models.BooleanField(default=False)),
                ('doblaje', models.BooleanField(default=False)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(max_length=500)),
                ('web', models.URLField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='plataformas/')),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
    ]
