# Generated by Django 6.1.1 on 2026-10-06 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='fecha_entrada_protectora',
            field=models.DateTimeField(null=True),
        ),
    ]
